#!/usr/bin/env bash
# Run prakash's Cyrius benchmark suite, append results to a CSV history, and
# regenerate benchmarks.md with a 3-point trend table (baseline → mid → current).
#
# Usage:
#   ./scripts/bench-history.sh                     # default CSV: bench-history.csv
#   ./scripts/bench-history.sh results.csv         # custom CSV
#   ./scripts/bench-history.sh "" tests/foo.bcyr   # custom suite
#
# `cyrius bench` emits one line per benchmark:
#   <name>: <avg><unit> avg (min=<..> max=<..>) [<n> iters]
# We record the reported avg (per iter), normalized to nanoseconds. The bench
# harness's fixed per-call overhead (~0.5-0.9us) is included, so the CSV tracks
# RELATIVE change across commits, not absolute op cost — the min in the raw
# output is the better absolute proxy.
set -euo pipefail

HISTORY_FILE="${1:-bench-history.csv}"
SUITE="${2:-tests/prakash.bcyr}"
BENCHMARKS_MD="benchmarks.md"
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
COMMIT=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
BRANCH=$(git branch --show-current 2>/dev/null || echo "unknown")

if [ ! -f "$HISTORY_FILE" ]; then
    echo "timestamp,commit,branch,benchmark,estimate_ns" > "$HISTORY_FILE"
fi

echo "╔══════════════════════════════════════════╗"
echo "║        prakash benchmark suite           ║"
echo "╠══════════════════════════════════════════╣"
echo "║  commit: $COMMIT"
echo "║  branch: $BRANCH"
echo "║  date:   $TIMESTAMP"
echo "║  suite:  $SUITE"
echo "╚══════════════════════════════════════════╝"
echo ""

BENCH_OUTPUT=$(cyrius bench "$SUITE" 2>&1 | sed 's/\x1b\[[0-9;]*m//g')
echo "$BENCH_OUTPUT"
echo ""

normalize_to_ns() {
    local val="$1" unit="$2"
    case "$unit" in
        ps)    awk -v v="$val" 'BEGIN{printf "%.4f", v / 1000}' ;;
        ns)    echo "$val" ;;
        us|µs) awk -v v="$val" 'BEGIN{printf "%.4f", v * 1000}' ;;
        ms)    awk -v v="$val" 'BEGIN{printf "%.4f", v * 1000000}' ;;
        s)     awk -v v="$val" 'BEGIN{printf "%.4f", v * 1000000000}' ;;
        *)     echo "$val" ;;
    esac
}

# Parse each "<name>: <avg><unit> avg (...)" line; the avg is the token before " avg".
while IFS= read -r line; do
    echo "$line" | grep -qE ':[[:space:]]*[0-9.]+[[:space:]]*(ps|ns|µs|us|ms|s)[[:space:]]+avg' || continue
    NAME=$(echo "$line" | sed -E 's/^[[:space:]]*//; s/:.*$//' | xargs)
    [ -z "$NAME" ] && continue
    TOKEN=$(echo "$line" | grep -oE '[0-9]+(\.[0-9]+)?[[:space:]]*(ps|ns|µs|us|ms|s)[[:space:]]+avg' | head -n1)
    VAL=$(echo "$TOKEN" | grep -oE '[0-9]+(\.[0-9]+)?' | head -n1)
    UNIT=$(echo "$TOKEN" | grep -oE '(ps|ns|µs|us|ms|s)[[:space:]]+avg' | grep -oE '(ps|ns|µs|us|ms|s)')
    NS=$(normalize_to_ns "$VAL" "$UNIT")
    echo "${TIMESTAMP},${COMMIT},${BRANCH},${NAME},${NS}" >> "$HISTORY_FILE"
done <<< "$BENCH_OUTPUT"

# 3-point trend table. Skip if Python missing — the CSV is the primary record.
command -v python3 >/dev/null 2>&1 || { echo "python3 absent — CSV updated, skipping benchmarks.md"; exit 0; }

python3 - "$HISTORY_FILE" "$BENCHMARKS_MD" "$COMMIT" <<'PYEOF'
import csv, sys
from collections import OrderedDict

history_file, md_file, cur_commit = sys.argv[1], sys.argv[2], sys.argv[3]
rows = list(csv.DictReader(open(history_file)))
if not rows:
    sys.exit(0)

stamps = list(OrderedDict.fromkeys(r["timestamp"] for r in rows))
if len(stamps) >= 3:
    pick = [stamps[0], stamps[len(stamps)//2], stamps[-1]]
elif len(stamps) == 2:
    pick = [stamps[0], stamps[-1]]
else:
    pick = [stamps[0]]
seen = set(); pick = [t for t in pick if not (t in seen or seen.add(t))]

data, commits = {}, {}
for r in rows:
    if r["timestamp"] in pick:
        try:
            data.setdefault(r["benchmark"], {})[r["timestamp"]] = float(r["estimate_ns"])
        except ValueError:
            continue
        commits[r["timestamp"]] = r["commit"]

labels = []
for i, ts in enumerate(pick):
    if i == 0 and len(pick) > 1:
        labels.append(f"Baseline (`{commits[ts]}`)")
    elif i == len(pick) - 1:
        labels.append(f"Current (`{commits[ts]}`)")
    else:
        labels.append(f"Mid (`{commits[ts]}`)")

def fmt(ns):
    if ns is None: return "—"
    if ns >= 1e6: return f"{ns/1e6:.3f} ms"
    if ns >= 1e3: return f"{ns/1e3:.3f} µs"
    return f"{ns:.1f} ns"

lines = ["# prakash benchmarks", "",
         "Cyrius benchmark history for the ported optics modules. Generated by",
         "`scripts/bench-history.sh` from `tests/prakash.bcyr`. Values are the",
         "harness-reported avg per iter (includes ~0.5–0.9µs fixed call overhead —",
         "track relative change, not absolute op cost).", "",
         "| Benchmark | " + " | ".join(labels) + " | Δ |", "|" + "---|" * (len(labels) + 2)]
for name in sorted(data):
    cells = [fmt(data[name].get(ts)) for ts in pick]
    first, last = data[name].get(pick[0]), data[name].get(pick[-1])
    delta = "—"
    if first and last and len(pick) > 1:
        pct = (last - first) / first * 100.0
        delta = f"{pct:+.1f}%"
    lines.append(f"| {name} | " + " | ".join(cells) + f" | {delta} |")
open(md_file, "w").write("\n".join(lines) + "\n")
print(f"benchmarks.md updated ({len(data)} benchmarks, {len(pick)} points)")
PYEOF
